pipeline {
    agent {
        stage('first'){
            Steps{
                echo "navneet"
            }
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -junit4-main clean package' 
            }
        }
    }
}
